import {visibleAdj} from './navigation-model.js';
import {terrainTypeAt} from './room-terrain.js?v=20260906-v3';

export const FACING_ORDER=['N','NE','E','SE','S','SW','W','NW'];
const NS='http://www.w3.org/2000/svg';
const W=800,H=450,HORIZON=224;
const FRAMES=[{l:-20,r:820,t:-10,b:470},{l:92,r:708,t:52,b:397},{l:188,r:612,t:112,b:337},{l:270,r:530,t:159,b:294},{l:326,r:474,t:188,b:268}];
const VECTORS={N:[0,-1],NE:[1,-1],E:[1,0],SE:[1,1],S:[0,1],SW:[-1,1],W:[-1,0],NW:[-1,-1]};
const UNIT={N:[0,-1],NE:[.7071,-.7071],E:[1,0],SE:[.7071,.7071],S:[0,1],SW:[-.7071,.7071],W:[-1,0],NW:[-.7071,-.7071]};
const PALETTES={
  A:{void:'#050403',stone:'#4a4032',stone2:'#6a5a45',stoneDark:'#211b15',floor:'#33291f',mortar:'#968069',water:'#102c31',accent:'#d59a4e',mist:'#74634d'},
  B:{void:'#020606',stone:'#35413b',stone2:'#59685b',stoneDark:'#17201d',floor:'#27312b',mortar:'#7c8b7d',water:'#062830',accent:'#c39758',mist:'#4e6d68'},
  C:{void:'#070304',stone:'#46342d',stone2:'#755247',stoneDark:'#231817',floor:'#34231f',mortar:'#956c5d',water:'#0a2529',accent:'#bf6845',mist:'#754e45'},
  D:{void:'#010405',stone:'#293735',stone2:'#52645f',stoneDark:'#111a1a',floor:'#1f2a27',mortar:'#6c827c',water:'#031e25',accent:'#74aaa0',mist:'#3b5a59'}
};

export function rotateFacing(facing,steps){const index=FACING_ORDER.indexOf(facing),start=index>=0?index:0;return FACING_ORDER[(start+steps%8+8)%8]}
export function relativeExitSide(facing,dir){const a=FACING_ORDER.indexOf(facing),b=FACING_ORDER.indexOf(dir);if(a<0||b<0)return null;const delta=(b-a+8)%8;if(delta===0)return 'front';if(delta===4)return 'back';if(delta<4)return 'right';return 'left'}
export function buildCrawlerAdj(map,dirs,sharedState=null){
  if(sharedState){const nav=visibleAdj(map,sharedState),adj=new Map(map.nodes.map(n=>[n.id,{}]));for(const [id,edges] of nav)for(const [dir,edge] of Object.entries(edges))adj.get(id)[dir]=edge.to;return adj}
  const adj=new Map(map.nodes.map(n=>[n.id,{}]));for(const [from,dir,to] of map.edges){if(!adj.has(from)||!adj.has(to))continue;const current=adj.get(from)[dir];if(current&&current!==to)throw new Error(`Conflicting crawler edge ${from}/${dir}`);adj.get(from)[dir]=to;const reverse=dirs[dir]?.opp;if(reverse&&!adj.get(to)[reverse])adj.get(to)[reverse]=from}return adj
}
export function traceSightline(map,dirs,nodeId,facing,maxDepth=4,sharedState=null){const adj=buildCrawlerAdj(map,dirs,sharedState),out=[];let current=nodeId;for(let depth=0;depth<maxDepth;depth++){const exits=adj.get(current)||{};out.push({node:current,exits:{...exits}});const next=exits[facing];if(!next)break;current=next}return out}

function el(name,attrs={}){const node=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,String(value));return node}
function append(parent,name,attrs={}){const node=el(name,attrs);parent.append(node);return node}
function polygon(parent,pts,className,attrs={}){return append(parent,'polygon',{points:pts.map(p=>p.join(',')).join(' '),class:className,...attrs})}
function path(parent,d,className,attrs={}){return append(parent,'path',{d,class:className,...attrs})}
function text(parent,value,attrs={}){const node=append(parent,'text',attrs);node.textContent=value;return node}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hashString(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function zoneFor(node){return Number(node?.z)===0?'A':Number(node?.z)===-1?'B':Number(node?.z)===-2?'C':'D'}
function nodeIsWet(node){return /Wasser|Zisterne|Brücke|Pump|Versunken|Feucht|Nass|Kaverne/i.test(node?.name||'')||node?.tags?.includes('water')}
function themeFor(node){const tags=new Set(node?.tags||[]),zone=zoneFor(node),shape=node?.geometry?.shape||'',name=node?.name||'';const cave=tags.has('cavern')||/cavern|grotte/i.test(shape)||/Grotte|Kaverne/i.test(name);const wet=nodeIsWet(node);return {zone,palette:PALETTES[zone],cave,wet,cult:tags.has('cult')||tags.has('demonic'),oldElem:tags.has('old_elem'),machinery:tags.has('machinery')||/machine|workshop|industrial/i.test(shape),grave:tags.has('grave')||/ossuary|burial/i.test(shape),pilgrim:tags.has('pilgrim'),shape,ceiling:Number(node?.geometry?.ceilingM)||4}}
function sceneType(node,theme){if(node?.id==='D14'||theme.cave)return 'cavern';if(node?.id==='D06'||theme.wet&&node?.exploreGrid)return 'waterhall';if(node?.kind==='lens')return 'lens';if(node?.kind==='prison')return 'cell';if(theme.machinery)return 'machinery';if(theme.cult)return 'cult';if(node?.geometry?.shape==='round_hall_complex'||node?.kind==='goal')return 'hall';return node?.exploreGrid?'chamber':'corridor'}

function installDefs(svg,theme){const p=theme.palette,defs=append(svg,'defs');defs.innerHTML=`
  <linearGradient id="v3Void" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.void}"/><stop offset=".56" stop-color="${p.stoneDark}"/><stop offset="1" stop-color="#010101"/></linearGradient>
  <linearGradient id="v3Floor" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.stoneDark}"/><stop offset="1" stop-color="${p.floor}"/></linearGradient>
  <linearGradient id="v3Water" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.water}"/><stop offset=".52" stop-color="#071b20"/><stop offset="1" stop-color="#01080a"/></linearGradient>
  <linearGradient id="v3Rock" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${p.stone2}"/><stop offset=".45" stop-color="${p.stone}"/><stop offset="1" stop-color="${p.stoneDark}"/></linearGradient>
  <radialGradient id="v3Torch"><stop offset="0" stop-color="#fff4c2" stop-opacity=".98"/><stop offset=".16" stop-color="${p.accent}" stop-opacity=".92"/><stop offset=".55" stop-color="${p.accent}" stop-opacity=".18"/><stop offset="1" stop-color="${p.accent}" stop-opacity="0"/></radialGradient>
  <radialGradient id="v3ColdGlow"><stop offset="0" stop-color="#9ad7d0" stop-opacity=".48"/><stop offset=".55" stop-color="#4d938c" stop-opacity=".13"/><stop offset="1" stop-color="#315f5a" stop-opacity="0"/></radialGradient>
  <radialGradient id="v3Vignette"><stop offset="48%" stop-color="#000" stop-opacity="0"/><stop offset="78%" stop-color="#000" stop-opacity=".28"/><stop offset="100%" stop-color="#000" stop-opacity=".84"/></radialGradient>
  <linearGradient id="v3Mist" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.mist}" stop-opacity="0"/><stop offset="1" stop-color="${p.mist}" stop-opacity=".16"/></linearGradient>
  <pattern id="v3Stone" width="96" height="48" patternUnits="userSpaceOnUse"><rect width="96" height="48" fill="${p.stone}"/><path d="M0 1h96M0 24h96M0 47h96M23 1v23M69 24v23" fill="none" stroke="${p.mortar}" stroke-opacity=".26" stroke-width="1"/><path d="M8 14l18-4M45 35l17-3M77 12l11 2" stroke="${p.stone2}" stroke-opacity=".22" stroke-width="2"/></pattern>
  <pattern id="v3FloorSlabs" width="110" height="72" patternUnits="userSpaceOnUse"><rect width="110" height="72" fill="${p.floor}"/><path d="M0 1h110M0 36h110M0 71h110M30 1v35M82 36v35" fill="none" stroke="${p.mortar}" stroke-opacity=".2" stroke-width="1"/><path d="M13 24l22-5M58 54l29-7" stroke="#050403" stroke-opacity=".28" stroke-width="2"/></pattern>
  <pattern id="v3Bridge" width="34" height="68" patternUnits="userSpaceOnUse"><rect width="34" height="68" fill="#443322"/><path d="M0 4h34M0 33h34M0 64h34" stroke="#8d6d48" stroke-opacity=".48" stroke-width="2"/><path d="M6 0v68M28 0v68" stroke="#1a120c" stroke-opacity=".35"/></pattern>
  <pattern id="v3RockFace" width="90" height="72" patternUnits="userSpaceOnUse"><rect width="90" height="72" fill="${p.stoneDark}"/><path d="M0 51L18 22 37 34 51 8 74 19 90 4v68H0z" fill="${p.stone}" fill-opacity=".62"/><path d="M7 55L31 39 48 46 69 31 87 42" fill="none" stroke="${p.stone2}" stroke-opacity=".34" stroke-width="3"/></pattern>
  <filter id="v3Shadow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur"/><feOffset dy="3" result="off"/><feColorMatrix in="off" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .65 0"/><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  <filter id="v3Glow" x="-180%" y="-180%" width="460%" height="460%"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  <clipPath id="v3StageClip"><rect x="0" y="0" width="800" height="450" rx="7"/></clipPath>`}

function drawAtmosphere(svg,theme){append(svg,'rect',{x:0,y:0,width:W,height:H,fill:'url(#v3Void)',class:'v3-backdrop'});append(svg,'ellipse',{cx:400,cy:285,rx:360,ry:155,fill:'url(#v3Mist)',class:'v3-depth-mist'});const seed=hashString(theme.zone+theme.shape);for(let i=0;i<9;i++){const x=50+((seed+i*137)%700),y=65+((seed*3+i*83)%290),r=.5+(i%3)*.35;append(svg,'circle',{cx:x,cy:y,r,class:'v3-mote'})}}
function drawVignette(svg){append(svg,'rect',{x:0,y:0,width:W,height:H,fill:'url(#v3Vignette)',class:'v3-vignette'})}
function drawTorch(svg,x,y,scale=1){const g=append(svg,'g',{class:'v3-torch'});append(g,'circle',{cx:x,cy:y,r:54*scale,fill:'url(#v3Torch)',class:'v3-torch-glow'});path(g,`M${x},${y+9*scale}q${-8*scale},${-14*scale} 0,${-30*scale}q${13*scale},${13*scale} 0,${30*scale}z`,'v3-flame');append(g,'line',{x1:x,y1:y+8*scale,x2:x,y2:y+27*scale,class:'v3-sconce'})}
function drawColdGlow(svg,x,y,rx=120,ry=55){append(svg,'ellipse',{cx:x,cy:y,rx,ry,fill:'url(#v3ColdGlow)',class:'v3-cold-glow'})}

function hasSideExit(exits,facing,side){return FACING_ORDER.some(dir=>exits[dir]&&relativeExitSide(facing,dir)===side)}
function drawArch(parent,frame,theme,depth=0){const cx=(frame.l+frame.r)/2,h=frame.b-frame.t,shoulder=frame.t+h*.38;path(parent,`M${frame.l} ${frame.b}L${frame.l} ${shoulder}Q${cx} ${frame.t-24} ${frame.r} ${shoulder}L${frame.r} ${frame.b}`,'v3-arch',{opacity:clamp(.9-depth*.16,.32,.9)});if(theme.oldElem)path(parent,`M${frame.l+9} ${shoulder+4}Q${cx} ${frame.t-8} ${frame.r-9} ${shoulder+4}`,'v3-arch-inlay',{opacity:clamp(.55-depth*.13,.16,.55)})}
function drawWallCourses(parent,outer,inner,side,depth){const opacity=clamp(.28-depth*.055,.08,.28);for(let i=1;i<4;i++){const t=i/4;const oy=outer.t+(outer.b-outer.t)*t,iy=inner.t+(inner.b-inner.t)*t;if(side==='left')append(parent,'line',{x1:outer.l,y1:oy,x2:inner.l,y2:iy,class:'v3-mortar-line',opacity});else append(parent,'line',{x1:outer.r,y1:oy,x2:inner.r,y2:iy,class:'v3-mortar-line',opacity})}}
function drawFloorSeams(parent,outer,inner,depth){const opacity=clamp(.23-depth*.04,.08,.23);append(parent,'line',{x1:(outer.l+outer.r)/2,y1:outer.b,x2:(inner.l+inner.r)/2,y2:inner.b,class:'v3-floor-seam',opacity});for(const k of [-.36,.36])append(parent,'line',{x1:400+k*(outer.r-outer.l),y1:outer.b,x2:400+k*(inner.r-inner.l),y2:inner.b,class:'v3-floor-seam',opacity})}
function drawSideOpening(parent,outer,inner,side,depth,theme){const y1=outer.t+(outer.b-outer.t)*.28,y2=outer.t+(outer.b-outer.t)*.78,iy1=inner.t+(inner.b-inner.t)*.31,iy2=inner.t+(inner.b-inner.t)*.74;if(side==='left'){polygon(parent,[[outer.l,y1],[inner.l+6,iy1],[inner.l+6,iy2],[outer.l,y2]],'v3-side-opening');path(parent,`M${outer.l} ${y2}L${outer.l} ${y1}Q${(outer.l+inner.l)/2} ${y1-26} ${inner.l+6} ${iy1}`,'v3-side-jamb')}else{polygon(parent,[[outer.r,y1],[inner.r-6,iy1],[inner.r-6,iy2],[outer.r,y2]],'v3-side-opening');path(parent,`M${outer.r} ${y2}L${outer.r} ${y1}Q${(outer.r+inner.r)/2} ${y1-26} ${inner.r-6} ${iy1}`,'v3-side-jamb')}if(theme.wet)append(parent,'line',{x1:side==='left'?outer.l:inner.r,y1:y2-3,x2:side==='left'?inner.l:outer.r,y2:iy2-2,class:'v3-water-edge',opacity:.45-depth*.08})}
function drawCorridorSegment(parent,outer,inner,depth,theme){const stone=theme.cave?'url(#v3RockFace)':'url(#v3Stone)',floor=theme.wet?'url(#v3Water)':'url(#v3FloorSlabs)';polygon(parent,[[outer.l,outer.t],[outer.r,outer.t],[inner.r,inner.t],[inner.l,inner.t]],'v3-corridor-ceiling',{fill:theme.cave?'url(#v3RockFace)':'url(#v3Rock)'});polygon(parent,[[outer.l,outer.b],[inner.l,inner.b],[inner.r,inner.b],[outer.r,outer.b]],`v3-corridor-floor${theme.wet?' wet':''}`,{fill:floor});polygon(parent,[[outer.l,outer.t],[inner.l,inner.t],[inner.l,inner.b],[outer.l,outer.b]],'v3-corridor-wall left',{fill:stone});polygon(parent,[[outer.r,outer.t],[outer.r,outer.b],[inner.r,inner.b],[inner.r,inner.t]],'v3-corridor-wall right',{fill:stone});if(theme.cave){path(parent,`M${inner.l} ${inner.b}Q${inner.l+18} ${inner.t+30} ${400-35} ${inner.t+13}Q400 ${inner.t-10} ${400+33} ${inner.t+15}Q${inner.r-18} ${inner.t+32} ${inner.r} ${inner.b}`,'v3-cave-rib',{opacity:clamp(.78-depth*.14,.28,.78)})}else drawArch(parent,inner,theme,depth);drawWallCourses(parent,outer,inner,'left',depth);drawWallCourses(parent,outer,inner,'right',depth);drawFloorSeams(parent,outer,inner,depth);if(theme.wet){const y=(outer.b+inner.b)/2;path(parent,`M${outer.l+14} ${y}Q400 ${y-8} ${outer.r-14} ${y}`,'v3-water-edge',{opacity:.36/(depth+1)})}}
function drawEndWall(parent,frame,node,theme,depth){if(theme.cave){polygon(parent,[[frame.l,frame.b],[frame.l-10,frame.t+48],[frame.l+27,frame.t+14],[400,frame.t-14],[frame.r-22,frame.t+18],[frame.r+8,frame.t+62],[frame.r,frame.b]],'v3-end-rock',{fill:'url(#v3RockFace)'});return}append(parent,'rect',{x:frame.l,y:frame.t,width:frame.r-frame.l,height:frame.b-frame.t,fill:'url(#v3Stone)',class:'v3-end-wall'});drawArch(parent,frame,theme,depth);if(node?.kind==='gate'||node?.id==='B12')drawGate(parent,frame);if(node?.kind==='prison')drawBars(parent,frame)}
function drawGate(parent,frame){const x1=frame.l+15,x2=frame.r-15,y1=frame.t+10,y2=frame.b-8;for(let x=x1;x<=x2;x+=Math.max(15,(x2-x1)/7))append(parent,'line',{x1:x,y1,x2:x,y2,class:'v3-gate-bar'});append(parent,'line',{x1,y1:y1+28,x2,y2:y1+28,class:'v3-gate-cross'});append(parent,'line',{x1,y1:y2-24,x2,y2:y2-24,class:'v3-gate-cross'})}
function drawBars(parent,frame){for(let x=frame.l+18;x<frame.r-12;x+=18)append(parent,'line',{x1:x,y1:frame.t+9,x2:x,y2:frame.b-8,class:'v3-prison-bar'})}
function drawCorridorScene(svg,map,node,facing,adj,theme){const byId=new Map(map.nodes.map(n=>[n.id,n]));let current=node;for(let depth=0;depth<4;depth++){const outer=FRAMES[depth],inner=FRAMES[depth+1],exits=adj.get(current.id)||{};drawCorridorSegment(svg,outer,inner,depth,themeFor(current));if(hasSideExit(exits,facing,'left'))drawSideOpening(svg,outer,inner,'left',depth,themeFor(current));if(hasSideExit(exits,facing,'right'))drawSideOpening(svg,outer,inner,'right',depth,themeFor(current));const h=hashString(current.id+facing);if(depth===0&&!theme.cave&&h%3!==0)drawTorch(svg,h%2?92:708,180,.7);if(depth===0&&theme.machinery)drawMachinery(svg);const nextId=exits[facing];if(!nextId){drawEndWall(svg,inner,current,themeFor(current),depth);break}const next=byId.get(nextId);if(!next){drawEndWall(svg,inner,current,themeFor(current),depth);break}current=next;if(depth===3)append(svg,'rect',{x:FRAMES[4].l,y:FRAMES[4].t,width:FRAMES[4].r-FRAMES[4].l,height:FRAMES[4].b-FRAMES[4].t,class:'v3-distance-dark'})}if(theme.cult)drawCultBanner(svg,72,118);if(theme.grave)drawNiches(svg)}

function basis(facing){const f=UNIT[facing]||UNIT.N;return {f,right:[-f[1],f[0]]}}
function roomCellProjection(pos,facing,x,y,cornerX=0,cornerY=0){const {f,right}=basis(facing),rx=(x+cornerX)-(pos.x+.5),ry=(y+cornerY)-(pos.y+.5),depth=rx*f[0]+ry*f[1],lateral=rx*right[0]+ry*right[1],z=Math.max(.24,depth+.9);return {x:400+lateral*190/z,y:HORIZON+205/z,depth,lateral,z}}
function roomFeatureProjection(pos,facing,x,y){const p=roomCellProjection(pos,facing,x,y,.5,.5);return {x:p.x,y:Math.min(395,p.y-8),depth:p.depth}}
function functionNameAnchor(){} // keep minifiers from collapsing named helper boundaries in source reviews
function terrainClass(type){return `crawler-terrain crawler-terrain-${type}`}
function drawTerrainPlane(parent,node,pos,facing){const grid=node.exploreGrid,cells=[];for(let y=0;y<grid.h;y++)for(let x=0;x<grid.w;x++){const center=roomCellProjection(pos,facing,x,y,.5,.5);if(center.depth<.05||center.depth>11)continue;const corners=[[0,0],[1,0],[1,1],[0,1]].map(([cx,cy])=>roomCellProjection(pos,facing,x,y,cx,cy));if(corners.some(p=>p.depth<-.55))continue;cells.push({x,y,depth:center.depth,corners,type:terrainTypeAt(node,x,y)})}cells.sort((a,b)=>b.depth-a.depth);for(const cell of cells){const pts=cell.corners.map(p=>[clamp(p.x,-250,1050),clamp(p.y,HORIZON-6,520)]);polygon(parent,pts,terrainClass(cell.type),{'data-cell':`${cell.x},${cell.y}`});if(cell.type==='deep_water'||cell.type==='shallow_water'){const a=pts[3],b=pts[2];append(parent,'line',{x1:a[0]+8,y1:a[1]-2,x2:b[0]-8,y2:b[1]-2,class:'v3-water-cell-glint'})}}}
function stepsToBoundary(pos,grid,facing){const [dx,dy]=VECTORS[facing]||[0,-1];let x=pos.x,y=pos.y,steps=0;while(steps<24){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=grid.w||ny>=grid.h)break;x=nx;y=ny;steps++}return steps}
function roomBackFrame(steps,theme){const d=clamp(steps,1,12),width=clamp(690/(1+d*.13),190,610),baseH=clamp(305/(1+d*.075)+theme.ceiling*3,132,310),centerY=HORIZON+18;return {l:400-width/2,r:400+width/2,t:centerY-baseH*.62,b:centerY+baseH*.38}}
function drawRoomShell(parent,node,theme,frame){if(theme.cave){append(parent,'rect',{x:0,y:0,width:W,height:H,fill:'url(#v3RockFace)',class:'v3-cavern-shell'});append(parent,'ellipse',{cx:400,cy:272,rx:350,ry:190,fill:'url(#v3Void)',class:'crawler-cavern-mouth'});path(parent,'M0 118Q85 35 164 86Q239 18 319 70Q399 4 478 68Q574 8 656 84Q737 43 800 115V0H0Z','v3-cavern-ceiling');polygon(parent,[[0,H],[frame.l,frame.b],[frame.l,frame.t],[0,76]],'v3-cavern-side left',{fill:'url(#v3RockFace)'});polygon(parent,[[W,H],[frame.r,frame.b],[frame.r,frame.t],[W,76]],'v3-cavern-side right',{fill:'url(#v3RockFace)'})}else{polygon(parent,[[0,0],[W,0],[frame.r,frame.t],[frame.l,frame.t]],'v3-room-ceiling',{fill:'url(#v3Rock)'});polygon(parent,[[0,H],[frame.l,frame.b],[frame.r,frame.b],[W,H]],'v3-room-floor',{fill:'url(#v3Floor)'});polygon(parent,[[0,0],[frame.l,frame.t],[frame.l,frame.b],[0,H]],'v3-room-wall left',{fill:'url(#v3Stone)'});polygon(parent,[[W,0],[W,H],[frame.r,frame.b],[frame.r,frame.t]],'v3-room-wall right',{fill:'url(#v3Stone)'});append(parent,'rect',{x:frame.l,y:frame.t,width:frame.r-frame.l,height:frame.b-frame.t,fill:'url(#v3Stone)',class:'v3-room-back'});drawArch(parent,frame,theme,0)}}
function drawPortal(parent,x,y,w,h,theme,variant='stone'){const g=append(parent,'g',{class:`v3-portal ${variant}`});const left=x-w/2,right=x+w/2,bottom=y+h/2,shoulder=y-h*.12,top=y-h/2;path(g,`M${left} ${bottom}L${left} ${shoulder}Q${x} ${top-18} ${right} ${shoulder}L${right} ${bottom}Z`,'v3-portal-dark');path(g,`M${left} ${bottom}L${left} ${shoulder}Q${x} ${top-18} ${right} ${shoulder}L${right} ${bottom}`,'v3-portal-frame');if(theme.oldElem)path(g,`M${left+8} ${shoulder+3}Q${x} ${top-7} ${right-8} ${shoulder+3}`,'v3-arch-inlay')}
function drawRoomExits(parent,exits,facing,frame,theme){if(exits[facing]){const w=Math.max(58,(frame.r-frame.l)*.27),h=Math.max(82,(frame.b-frame.t)*.66);drawPortal(parent,400,frame.b-h/2,w,h,theme)}if(hasSideExit(exits,facing,'left'))drawPortal(parent,66,282,118,210,theme,'side left');if(hasSideExit(exits,facing,'right'))drawPortal(parent,734,282,118,210,theme,'side right')}

function drawPedestal(parent,x,y,scale=1,green=false){append(parent,'ellipse',{cx:x,cy:y+12*scale,rx:58*scale,ry:16*scale,class:'v3-pedestal-shadow'});polygon(parent,[[x-40*scale,y],[x+40*scale,y],[x+28*scale,y+48*scale],[x-28*scale,y+48*scale]],'v3-pedestal');append(parent,'ellipse',{cx:x,cy:y,rx:43*scale,ry:12*scale,class:'v3-pedestal-top'});if(green){append(parent,'ellipse',{cx:x,cy:y-4*scale,rx:27*scale,ry:8*scale,class:'v3-green-socket'});append(parent,'ellipse',{cx:x,cy:y-4*scale,rx:48*scale,ry:18*scale,fill:'url(#v3ColdGlow)',class:'v3-socket-glow'})}}
function drawProjectedPillar(parent,x,y,h=130,scale=1,broken=false){const w=24*scale,hh=h*scale;append(parent,'ellipse',{cx:x,cy:y+3,rx:w*.8,ry:w*.23,class:'v3-pillar-shadow'});append(parent,'rect',{x:x-w/2,y:y-hh,width:w,height:hh,rx:3,class:`crawler-projected-pillar${broken?' broken':''}`});append(parent,'ellipse',{cx:x,cy:y-hh,rx:w*.63,ry:w*.21,class:'v3-pillar-cap'});if(broken)path(parent,`M${x-w/2} ${y-hh+4}l${w*.28} -8 ${w*.23} 7 ${w*.27} -9 ${w*.22} 8`,'v3-pillar-break')}
function drawRitualDais(parent){const g=append(parent,'g',{class:'v3-ritual-setpiece'});append(g,'ellipse',{cx:400,cy:346,rx:134,ry:43,class:'crawler-ritual-dais'});append(g,'ellipse',{cx:400,cy:339,rx:104,ry:31,class:'v3-ritual-ring outer'});append(g,'ellipse',{cx:400,cy:339,rx:67,ry:20,class:'v3-ritual-ring inner'});append(g,'ellipse',{cx:400,cy:339,rx:21,ry:8,class:'v3-ritual-core'});for(let i=0;i<8;i++){const a=i*Math.PI/4,x=400+Math.cos(a)*91,y=339+Math.sin(a)*25;append(g,'line',{x1:400,y1:339,x2:x,y2:y,class:'v3-ritual-spoke'})}}
function drawStalactites(parent,count=7){for(let i=0;i<count;i++){const x=70+i*(660/(count-1)),h=45+(i*31)%90,w=17+(i*13)%20;polygon(parent,[[x-w,0],[x+w,0],[x+5,h],[x,h+28],[x-6,h]],'crawler-stalactite')}}
function drawMachinery(parent){path(parent,'M30 104H142V178H188','v3-pipe');path(parent,'M770 122H688V205H648','v3-pipe');append(parent,'circle',{cx:142,cy:178,r:16,class:'v3-valve'});append(parent,'circle',{cx:688,cy:205,r:14,class:'v3-valve'});for(const [cx,cy] of [[142,178],[688,205]])for(let i=0;i<4;i++){const a=i*Math.PI/2;append(parent,'line',{x1:cx,y1:cy,x2:cx+Math.cos(a)*23,y2:cy+Math.sin(a)*23,class:'v3-valve-spoke'})}}
function drawCultBanner(parent,x,y){polygon(parent,[[x,y],[x+54,y+4],[x+47,y+121],[x+27,y+108],[x+8,y+123]],'v3-cult-banner');path(parent,`M${x+17} ${y+29}Q${x+28} ${y+13} ${x+39} ${y+29}Q${x+28} ${y+47} ${x+17} ${y+29}`,'v3-banner-glyph')}
function drawNiches(parent){for(const x of [58,122,678,742]){append(parent,'rect',{x:x-23,y:150,width:46,height:92,rx:20,class:'v3-grave-niche'});append(parent,'ellipse',{cx:x,cy:206,rx:9,ry:14,class:'v3-skull-mark'})}}
function drawDesk(parent){polygon(parent,[[318,331],[482,331],[456,370],[344,370]],'v3-desk');append(parent,'line',{x1:352,y1:370,x2:350,y2:408,class:'v3-desk-leg'});append(parent,'line',{x1:448,y1:370,x2:450,y2:408,class:'v3-desk-leg'});append(parent,'rect',{x:374,y:337,width:52,height:24,rx:3,class:'v3-paper'});drawTorch(parent,456,324,.42)}
function drawThreshold(parent){for(let i=0;i<5;i++){const y=290+i*23,pathW=55+i*34;path(parent,`M${400-pathW} ${y}Q400 ${y-12} ${400+pathW} ${y}`,'v3-threshold-glyph',{opacity:.8-i*.11})}append(parent,'line',{x1:400,y1:265,x2:400,y2:418,class:'v3-threshold-axis'})}
function drawLens(parent,x=400,y=300,scale=1){append(parent,'circle',{cx:x,cy:y,r:52*scale,class:'crawler-lens-ring'});append(parent,'circle',{cx:x,cy:y,r:36*scale,class:'v3-lens-core'});append(parent,'circle',{cx:x,cy:y,r:78*scale,fill:'url(#v3ColdGlow)',class:'v3-lens-glow'});for(let i=0;i<6;i++){const a=i*Math.PI/3;append(parent,'line',{x1:x+Math.cos(a)*53*scale,y1:y+Math.sin(a)*53*scale,x2:x+Math.cos(a)*71*scale,y2:y+Math.sin(a)*71*scale,class:'v3-lens-strut'})}}
function drawFloodedPillars(parent,variant='hall'){const coords=variant==='cavern'?[[182,340,122,1.05],[302,319,92,.8],[515,345,148,1.12],[633,315,80,.72]]:[[205,350,116,1],[342,330,84,.78],[496,350,132,1.06],[620,326,75,.72]];for(let i=0;i<coords.length;i++){const [x,y,h,s]=coords[i];drawProjectedPillar(parent,x,y,h,s,i%2===1)}}
function drawSetpiece(parent,node,theme){if(node.id==='A06'){drawPedestal(parent,400,328,1.05,true);drawTorch(parent,196,232,.52);drawTorch(parent,604,232,.52)}if(node.id==='B12'){drawGate(parent,{l:285,r:515,t:146,b:340});drawColdGlow(parent,400,310,120,58)}if(node.id==='C10'){drawBars(parent,{l:270,r:530,t:138,b:354});append(parent,'ellipse',{cx:360,cy:360,rx:55,ry:12,class:'v3-bedding'})}if(node.id==='C12')drawThreshold(parent);if(node.id==='C14'){drawDesk(parent);drawCultBanner(parent,92,130)}if(node.id==='C15'){drawRitualDais(parent);drawProjectedPillar(parent,236,352,150,.95);drawProjectedPillar(parent,320,318,103,.72);drawProjectedPillar(parent,480,318,103,.72);drawProjectedPillar(parent,564,352,150,.95);drawTorch(parent,281,310,.48);drawTorch(parent,519,310,.48)}if(node.id==='D06'){drawFloodedPillars(parent,'hall');drawColdGlow(parent,400,378,310,72)}if(node.id==='D12'){drawPedestal(parent,400,345,.92,false);drawLens(parent,400,281,.88)}if(node.id==='D14'){drawStalactites(parent,9);drawFloodedPillars(parent,'cavern');drawColdGlow(parent,400,390,360,80)}if(node.kind==='lens'&&!['A06','D12'].includes(node.id))drawLens(parent,400,305,.72);if(theme.machinery)drawMachinery(parent);if(theme.grave)drawNiches(parent);if(theme.cult&&!['C14','C15'].includes(node.id))drawCultBanner(parent,78,128)}
function drawRoomLights(parent,node,theme){const seed=hashString(node.id);if(theme.zone==='D'){drawColdGlow(parent,400,386,260,64);return}if(theme.cave)return;if(seed%2===0)drawTorch(parent,112,220,.58);if(seed%3!==0)drawTorch(parent,688,220,.58)}
function drawFeatureMarkers(parent,state,pos,facing){for(const [i,feature] of (state.visibleFeatures||[]).slice(0,4).entries()){if(!Number.isFinite(feature.x)||!Number.isFinite(feature.y))continue;const p=roomFeatureProjection(pos,facing,feature.x,feature.y);if(p.depth<-.2||p.depth>10)continue;const y=clamp(p.y,250,399),x=clamp(p.x,88,712),g=append(parent,'g',{class:'v3-feature-marker'});append(g,'circle',{cx:x,cy:y,r:6,class:'v3-feature-dot'});if(feature.label){const label=String(feature.label).slice(0,26),w=Math.min(150,30+label.length*5.4),tx=clamp(x,90+w/2,710-w/2);append(g,'rect',{x:tx-w/2,y:y+10,width:w,height:22,rx:11,class:'v3-feature-label-bg'});text(g,label,{x:tx,y:y+25,class:'v3-feature-label'})}if(i===3)break}}
function renderRoomScene(svg,node,exits,state,theme){const grid=state.roomGrid,pos=state.heroPosition,facing=state.facing,steps=stepsToBoundary(pos,grid,facing),frame=roomBackFrame(steps,theme);drawRoomShell(svg,node,theme,frame);drawTerrainPlane(svg,node,pos,facing);drawRoomExits(svg,exits,facing,frame,theme);drawRoomLights(svg,node,theme);drawSetpiece(svg,node,theme);drawFeatureMarkers(svg,state,pos,facing);const meta=`${grid.w*3} × ${grid.h*3} m · ${theme.ceiling} m hoch`;text(svg,meta,{x:400,y:432,class:'v3-room-scale'})}

function renderScene(svg,map,dirs,state){if(!svg)return;const byId=new Map(map.nodes.map(n=>[n.id,n])),node=byId.get(state.node);if(!node)return;const facing=FACING_ORDER.includes(state.facing)?state.facing:'N',adj=buildCrawlerAdj(map,dirs,state.sharedState||null),exits=adj.get(node.id)||{},theme=themeFor(node);svg.dataset.level=String(node.z);svg.dataset.zone=theme.zone;svg.dataset.room=node.id;svg.dataset.scene=sceneType(node,theme);svg.replaceChildren();installDefs(svg,theme);drawAtmosphere(svg,theme);const content=append(svg,'g',{class:'v3-scene',clipPath:'url(#v3StageClip)'});if(state.roomGrid&&state.heroPosition)renderRoomScene(content,node,exits,{...state,facing},theme);else drawCorridorScene(content,map,node,facing,adj,theme);drawVignette(svg)}

export function createCrawlerView({map,dirs,getState}){const svg=document.querySelector('#crawlerSvg'),facingLabel=document.querySelector('#crawlerFacing'),currentTitle=document.querySelector('#crawlerCurrent');return {render(){const state=getState();if(!state?.node)return;const node=map.nodes.find(n=>n.id===state.node),facing=FACING_ORDER.includes(state.facing)?state.facing:'N';renderScene(svg,map,dirs,{...state,facing});if(facingLabel)facingLabel.textContent=`Blick ${dirs[facing]?.label||facing}`;if(currentTitle)currentTitle.textContent=node?.name||state.node},setMode(next){document.body.classList.toggle('view-crawler',next!=='map');document.body.classList.toggle('view-map',next==='map')}}}
